### ISSUE TITLE
mouse cursor is not pointer

### ISSUE THREAD

**Issue by snowcxt** [YouCanBookMe/react-datetime#38]
Just update to 2.0.0. The hover over cursor is 'text' but expect 'pointer'

**Comment by mqklin** [comment]
I solved it with this:
```
.rdt input:hover {
  cursor: pointer;
}
```

**Comment by snowcxt** [comment]
Doesn't work for me. My code:
```css
.rdtDay {
  cursor: pointer;
}
```
